# Generated by Django 4.2.7 on 2025-12-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_seed_initial_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Stored for admin visibility (Insecure)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('USER', 'User (Student)')], default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='ideal_answer',
            field=models.TextField(blank=True, help_text='Required if source_type is MANUAL. Optional if using links.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, help_text='Required if source_type is MANUAL. Optional if using links.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='access_type',
            field=models.CharField(blank=True, choices=[('TRIAL', 'Trial - One Free Interview'), ('FULL', 'Full Access - Unlimited Interviews')], default='TRIAL', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
