# Generated by Django 4.2.7 on 2025-12-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_add_role_and_password_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='accuracy_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='completeness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='score_breakdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
