# Generated by Django 4.2.7 on 2025-12-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_update_admin_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['topic', 'id']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
    ]
