# Generated by Django 4.2.7 on 2025-12-29 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_round_question_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='interview.round'),
        ),
    ]
